<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cb-ScreenSizeDetail</name>
   <tag></tag>
   <elementGuidId>279f9825-618e-44bb-8123-1e3ee1eb1fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;c3-subPanel-Screen%20Size_4.0%20-%204.4%20in-0_cbx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;c3-subPanel-Screen%20Size_4.0%20-%204.4%20in-0_cbx&quot;]</value>
   </webElementProperties>
</WebElementEntity>
