<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb-ItemLocationDetail</name>
   <tag></tag>
   <elementGuidId>2954bc35-d085-4c1f-91af-f6f087c5771b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;c3-subPanel-location_Asia-0_rbx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;c3-subPanel-location_Asia-0_rbx&quot;]</value>
   </webElementProperties>
</WebElementEntity>
