<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-ListDropdown</name>
   <tag></tag>
   <elementGuidId>89ab99d1-c2fe-4f80-9aba-e6caf98d0141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;user-links&quot;]/details/details-menu/a[text()='${varList}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;user-links&quot;]/details/details-menu/a[text()='${varList}']</value>
   </webElementProperties>
</WebElementEntity>
