<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-GistTypeDetail</name>
   <tag></tag>
   <elementGuidId>65a55f08-db44-4ad5-9b56-102d5c8e6348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;new_gist&quot;]/div/div[2]/div/details/details-menu/label[*]/div/span[text()='${varGistType}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;new_gist&quot;]/div/div[2]/div/details/details-menu/label[*]/div/span[text()='${varGistType}']</value>
   </webElementProperties>
</WebElementEntity>
