<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt-FileName</name>
   <tag></tag>
   <elementGuidId>8231f073-8124-45f4-93d3-c265835e8198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;gists&quot;]/div[2]/div/div[1]/div[1]/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;gists&quot;]/div[2]/div/div[1]/div[1]/input[2]</value>
   </webElementProperties>
</WebElementEntity>
