<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt-AllFile</name>
   <tag></tag>
   <elementGuidId>d75cc4ef-2d48-475e-af3f-fe3b438afcd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;gist-pjax-container&quot;]/div/div/div[2]//div[1]//strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;gist-pjax-container&quot;]/div/div/div[2]//div[1]//strong</value>
   </webElementProperties>
</WebElementEntity>
