<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-MoreFilters</name>
   <tag></tag>
   <elementGuidId>8b27667d-7419-4c43-9d5b-f7667ec1c75d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;s0-14-11-0-1-2-6-2&quot;]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;s0-14-11-0-1-2-6-2&quot;]/button</value>
   </webElementProperties>
</WebElementEntity>
