<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl-SearchResult</name>
   <tag></tag>
   <elementGuidId>1ebaac20-f9ab-4c1d-a7be-67ef8196252a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;srp-river-results&quot;]/ul/li[*]/div/div[2]/a/h3/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;srp-river-results&quot;]/ul/li[*]/div/div[2]/a/h3/span</value>
   </webElementProperties>
</WebElementEntity>
